@baseURL = http://<HOST>:<PORT>/api/notes

###
GET {{baseURL}}

###
GET {{baseURL}}/:id

###
POST {{baseURL}}
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
    "content": "content test"
}

###
PUT {{baseURL}}/:id
Content-Type: application/json

{
    "content": "content test update",
    "important": true
}

###
DELETE {{baseURL}}/:id