@baseURL = http://<HOST>:<PORT>/api

###
GET {{baseURL}}/notes

###
GET {{baseURL}}/notes/:id

###
POST {{baseURL}}/notes
Content-Type: application/json

{
    "content": "testt"
}

###
PUT {{baseURL}}/notes/:id
Content-Type: application/json

{
    "content": "testt",
    "important": true
}

###
DELETE {{baseURL}}/notes/:id