@baseURL = http://<HOST>:<PORT>

### 
GET {{baseURL}}/api/persons

### 
GET {{ baseURL }}/api/persons/:id

### 
GET {{ baseURL }}/info

### 
POST {{ baseURL }}/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": 111
}

###
PUT {{baseURL}}/api/persons/:id
Content-Type: application/json

{
    "name": "test",
    "number": 111
}

### 
DELETE {{ baseURL }}/api/persons/:id