@baseURL = http://<HOST>:<PORT>

### 
GET {{baseURL}}/api/persons

### 
GET {{ baseURL }}/api/persons/3

### 
GET {{ baseURL }}/info

### 
POST {{ baseURL }}/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "test"
}

### 
DELETE {{ baseURL }}/api/persons/3